In this collab we generate node embeddings with the help of Metapath2Vec and then calculate cuisine similarity between them. The goal is to find the most similar recipes according to the cosine similarity.

In [ ]:
!pip install stellargraph

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
users = pd.read_csv("/content/drive/MyDrive/food recipes/PP_users.csv")
recipes = pd.read_csv("/content/drive/MyDrive/food recipes/PP_recipes.csv")
interactions = pd.read_csv("/content/drive/MyDrive/food recipes/interactions_train.csv")

**Find unique users & recipes and give them appropriate indexes**

In [ ]:
users = interactions['u'].unique()
users = pd.DataFrame(users, columns=['u'])
users = users.set_index("user_"+users.index.astype(str))
users

u
user_0      22095
user_1      24732
user_2       1674
user_3      20667
user_4      19047
...           ...
user_25071  18127
user_25072   5201
user_25073  13311
user_25074   7790
user_25075  14897

[25076 rows x 1 columns]

In [ ]:
recipes = interactions['i'].unique()
recipes = pd.DataFrame(recipes, columns=["i"])
recipes = recipes.set_index('recipe_'+recipes.index.astype(str))
recipes 

i
recipe_0        44367
recipe_1        87844
recipe_2       138181
recipe_3        93054
recipe_4       101723
...               ...
recipe_160896   35126
recipe_160897  112580
recipe_160898   89109
recipe_160899   51525
recipe_160900   18120

[160901 rows x 1 columns]

In [ ]:
interactions

user_id  recipe_id        date  rating      u       i
0             2046       4684  2000-02-25     5.0  22095   44367
1             2046        517  2000-02-25     5.0  22095   87844
2             1773       7435  2000-03-13     5.0  24732  138181
3             1773        278  2000-03-13     4.0  24732   93054
4             2046       3431  2000-04-07     5.0  22095  101723
...            ...        ...         ...     ...    ...     ...
698896      926904     457971  2018-12-18     5.0  13681  141067
698897  2002312797      27208  2018-12-18     5.0  14897   99787
698898     1290903     131607  2018-12-18     5.0  11605   76163
698899      226867     363072  2018-12-18     5.0   3604   29101
698900  2000498330     314535  2018-12-19     5.0   2248   21514

[698901 rows x 6 columns]

In [ ]:
edges = pd.read_csv("/content/drive/MyDrive/food recipes/edges_final.csv")
edges.drop(['Unnamed: 0'], axis=1, inplace=True)
edges

target         source        date
0           user_0       recipe_0  2000-02-25
1           user_0       recipe_1  2000-02-25
2           user_1       recipe_2  2000-03-13
3           user_1       recipe_3  2000-03-13
4           user_0       recipe_4  2000-04-07
...            ...            ...         ...
698896  user_21665  recipe_142940  2018-12-18
698897  user_25075    recipe_2669  2018-12-18
698898  user_22591   recipe_49370  2018-12-18
698899  user_10668  recipe_134757  2018-12-18
698900  user_24656  recipe_114304  2018-12-19

[698901 rows x 3 columns]

**Create the graph**

In [ ]:
from stellargraph import StellarGraph

edges_graph = edges.drop(['date'], axis=1)
graph = StellarGraph({"users":users, "recipes":recipes}, edges_graph)
print(graph.info())

StellarGraph: Undirected multigraph
 Nodes: 185977, Edges: 698901

 Node types:
  recipes: [160901]
    Features: float32 vector, length 1
    Edge types: recipes-default->users
  users: [25076]
    Features: float32 vector, length 1
    Edge types: users-default->recipes

 Edge types:
    recipes-default->users: [698901]
        Weights: all 1 (default)
        Features: none


# **Metapath2Vec**

In [ ]:
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
import os
import networkx as nx
import numpy as np
import pandas as pd
from stellargraph import datasets
from IPython.display import display, HTML

%matplotlib inline

In [ ]:
walk_length = 120  # maximum length of a random walk to use throughout this notebook

# specify the metapath schemas as a list of lists of node types.
metapaths = [
    ["users", "recipes", "users"],
    ["recipes", "users", "users", "recipes"],
    ["recipes", "recipes"],
]

In [ ]:
from stellargraph.data import UniformRandomMetaPathWalk

# Create the random walker
rw = UniformRandomMetaPathWalk(graph)

walks = rw.run(
    nodes=list(graph.nodes()),  # root nodes
    length=walk_length,  # maximum length of a random walk
    n=1,  # number of random walks per root node
    metapaths=metapaths,  # the metapaths
)

print("Number of random walks: {}".format(len(walks)))

Number of random walks: 346878


In [ ]:
from gensim.models import Word2Vec

model = Word2Vec(walks, size=128, window=5, min_count=0, sg=1, workers=2, iter=1)

In [ ]:
model.wv.vectors.shape 

(185977, 128)

In [ ]:
# Retrieve node embeddings and corresponding subjects
node_ids = model.wv.index2word  # list of node IDs
node_embeddings = (
    model.wv.vectors
)
node_embeddings

array([[ 4.9685150e-02,  2.5385190e-02, -1.4418734e-03, ...,
         8.9795506e-03,  4.4722357e-03, -1.1564555e-02],
       [ 2.0248305e-02, -1.3669088e-02,  2.2583427e-04, ...,
        -5.1572354e-04,  1.2055436e-02, -2.1957196e-02],
       [ 8.8100694e-03, -1.2057280e-02,  1.9685335e-03, ...,
         2.0633705e-02, -1.4310701e-02, -8.3530759e-03],
       ...,
       [-1.0182718e-03, -2.8971757e-03,  5.1995332e-04, ...,
         2.8876609e-03, -2.2294440e-03,  4.4694720e-05],
       [-3.0971675e-03,  3.0562051e-03, -1.2397080e-03, ...,
        -8.8931993e-04, -3.0645297e-03,  3.8372127e-03],
       [-3.7197389e-03,  1.2593233e-03, -3.6064521e-03, ...,
        -3.3696310e-03, -2.1357776e-03,  3.0402397e-04]], dtype=float32)

In [ ]:
!pip install sentence-transformers

In [ ]:
import pandas as pd
import numpy as np
import os 
import ast
import sentence_transformers  #### This is the package which we will use for encoding recipes using pretrained embedding
import matplotlib.pyplot as plt 
import networkx as nx #### Network x will be used to create graph based algorithms
import pickle ### We will use pickleto save files for later access
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity ### Cuisine Similary
from scipy import sparse ### Sparse Matrix
model = SentenceTransformer('bert-large-nli-stsb-mean-tokens') ### We will use this sentence encodings

Some weights of the model checkpoint at /root/.cache/torch/sentence_transformers/sbert.net_models_bert-large-nli-stsb-mean-tokens/0_BERT were not used when initializing BertModel: ['classifier.weight', 'classifier.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
all_embeddings = np.load('/content/drive/MyDrive/food recipes/embeddings.npy')
all_embeddings

array([[ 4.9685150e-02,  2.5385190e-02, -1.4418734e-03, ...,
         8.9795506e-03,  4.4722357e-03, -1.1564555e-02],
       [ 2.0248305e-02, -1.3669088e-02,  2.2583427e-04, ...,
        -5.1572354e-04,  1.2055436e-02, -2.1957196e-02],
       [ 8.8100694e-03, -1.2057280e-02,  1.9685335e-03, ...,
         2.0633705e-02, -1.4310701e-02, -8.3530759e-03],
       ...,
       [-1.0182718e-03, -2.8971757e-03,  5.1995332e-04, ...,
         2.8876609e-03, -2.2294440e-03,  4.4694720e-05],
       [-3.0971675e-03,  3.0562051e-03, -1.2397080e-03, ...,
        -8.8931993e-04, -3.0645297e-03,  3.8372127e-03],
       [-3.7197389e-03,  1.2593233e-03, -3.6064521e-03, ...,
        -3.3696310e-03, -2.1357776e-03,  3.0402397e-04]], dtype=float32)

In [ ]:
all_embeddings = np.array(node_embeddings)

In [ ]:
np.save('/content/drive/MyDrive/food recipes/embeddings.npy', all_embeddings)

In [ ]:
test = all_embeddings[:10000]

In [ ]:
result = cosine_similarity(test)

In [ ]:
result

array([[ 0.99999994,  0.10762647,  0.2445693 , ..., -0.06991005,
        -0.00136704, -0.09638256],
       [ 0.10762647,  0.9999999 ,  0.19804443, ..., -0.07662005,
         0.08817258, -0.0758438 ],
       [ 0.2445693 ,  0.19804443,  0.9999998 , ..., -0.02602956,
        -0.05381593, -0.10568848],
       ...,
       [-0.06991005, -0.07662005, -0.02602956, ...,  0.9999999 ,
        -0.08281579,  0.06086101],
       [-0.00136704,  0.08817258, -0.05381593, ..., -0.08281579,
         1.        ,  0.11282407],
       [-0.09638256, -0.0758438 , -0.10568848, ...,  0.06086101,
         0.11282407,  1.0000001 ]], dtype=float32)

In [ ]:
df1 = pd.DataFrame(result)
pickle.dump(df1,open('result_similarity.pickle','wb'))

In [ ]:
df1

0         1         2     ...      9997      9998      9999
0     1.000000  0.107626  0.244569  ... -0.069910 -0.001367 -0.096383
1     0.107626  1.000000  0.198044  ... -0.076620  0.088173 -0.075844
2     0.244569  0.198044  1.000000  ... -0.026030 -0.053816 -0.105688
3     0.387225  0.017539  0.195981  ...  0.032434  0.053072 -0.090863
4     0.149793  0.225090  0.292916  ... -0.008231 -0.069738  0.023420
...        ...       ...       ...  ...       ...       ...       ...
9995 -0.025019  0.058877  0.060330  ...  0.117226 -0.052421  0.036444
9996  0.005435 -0.168570  0.105475  ... -0.039985 -0.087027  0.092553
9997 -0.069910 -0.076620 -0.026030  ...  1.000000 -0.082816  0.060861
9998 -0.001367  0.088173 -0.053816  ... -0.082816  1.000000  0.112824
9999 -0.096383 -0.075844 -0.105688  ...  0.060861  0.112824  1.000000

[10000 rows x 10000 columns]

In [ ]:
data_similarity = df1.unstack().reset_index()

In [ ]:
data_similarity.columns = ['recipe1','recipe2','cosine_similarity']

In [ ]:
data_similarity

recipe1  recipe2  cosine_similarity
0               0        0           1.000000
1               0        1           0.107626
2               0        2           0.244569
3               0        3           0.387225
4               0        4           0.149793
...           ...      ...                ...
99999995     9999     9995           0.036444
99999996     9999     9996           0.092553
99999997     9999     9997           0.060861
99999998     9999     9998           0.112824
99999999     9999     9999           1.000000

[100000000 rows x 3 columns]

In [ ]:
data_similarity = data_similarity[data_similarity['cosine_similarity']<0.9999]
data_similarity = data_similarity[data_similarity['cosine_similarity']>0.3]
print (data_similarity.shape)

(31646, 3)


In [ ]:
data_similarity

recipe1  recipe2  cosine_similarity
3               0        3           0.387225
23              0       23           0.366096
63              0       63           0.366290
280             0      280           0.325494
2250            0     2250           0.347412
...           ...      ...                ...
99988254     9998     8254           0.327445
99993621     9999     3621           0.306014
99993993     9999     3993           0.303178
99994765     9999     4765           0.328923
99999883     9999     9883           0.347560

[31646 rows x 3 columns]